### ISSUE TITLE
Running the build script

### ISSUE THREAD

**Issue by mojtaba-komeili** [JerichoWorld/JerichoWorld#1]
I tried to run the `build_dataset.py` file to build the dataset, but it crashed. The`defines_updated` module import ([link](https://github.com/JerichoWorld/JerichoWorld/blob/f65101daa2100ee85aa6307e2d87bd2fe0221aeb/build_dataset.py#L7)) seems to be the issue.

**Comment by JerichoWorld** [comment]
Thanks for finding this. Should be fixed with dab6655.

**Comment by mojtaba-komeili** [comment]
Thanks for your quick response. But that might still be missing [this](https://github.com/JerichoWorld/JerichoWorld/blob/dab66552e8b11b8d8c0149452d606b6a27f0b697/defines_updated.py#L5) import.

**Comment by mojtaba-komeili** [comment]
Ahh, actually never mind. I just saw you just patched that as well. Thanks!
