### ISSUE TITLE
Number of samples in each game

### ISSUE THREAD

**Issue by mojtaba-komeili** [JerichoWorld/JerichoWorld#4]
While using your dataset, I noticed that number of samples are not matching the dataset statistics reported in Table 1 in your paper. For example 
```python
with open('/path/data/jericho/train.json', 'r') as fi:
    td = json.load(fi)

for arb_game_ids in (3, 7, 12):
    g = td[arb_game_ids]
    print(f'{g[0]["rom"]}: {len(g)}')
    
# output
# zork2: 292
# 905: 252
# murdac: 957
```

But in the paper they are reported to have 

| Game   | Number of samples |
|--------|-------------------|
| zork2  | 584               |
| 905    | 504               |
| murdac | 1914              |

Basically, every number I checked was half of what it was in the paper. Are there some missing examples here or there is something else that I missed? I appreciate your response. Thank you!

PS. the fact that the number of samples for every game in the table is even is a bit odd (no pun intended 😄 ).

**Comment by yukw777** [comment]
I believe this is b/c each datapoint has two states, the current and the next. In the paper, I believe they reported the number of these sampled states.
